[features]
seeds = false
skip-lint = false
[programs.devnet]
# localnet:
# solana = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
# devnet:
solana = "4VSzZUMRLSBqoXjepkU7ZNzN3EhPoCx4B4Au6XdQbv6N"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lyczek/.config/solana/id.json"

[scripts]
test = "node tests/solana.js"
