[features]
seeds = false
skip-lint = false
# devnet:
[programs.devnet]
solana = "4VSzZUMRLSBqoXjepkU7ZNzN3EhPoCx4B4Au6XdQbv6N"

# localnet:
# [programs.localnet]
# solana = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"



[registry]
url = "https://api.apr.dev"

[provider]
# devnet:
cluster = "devnet"

# localnet:
# cluster = "localnet"

wallet = "/home/lyczek/.config/solana/id.json"

[scripts]
test = "node tests/solana.js"
